### ISSUE TITLE
Minimize and maximize feature is not working correctly

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/FancyBox#59]
https://community.mybb.com/thread-219143-post-1331991.html#pid1331991

#2

I think we should disable this by default and add a note to ACP that this is highly experimental feature... I dont know how to fix that (it is not trivial and I am not a JS guy).

**Comment by lairdshaw** [comment]
It looks to me that this bug is caused by [line 65](https://github.com/mybbgroup/FancyBox/blob/df926198ea9091726f1e9c7e3348fe93037127f0/jscripts/mybbfancybox.js#L65) of `jscripts/mybbfancybox.js`. Commenting that line out resolves the bug.

Commenting out the line doesn't seem to have any side-effects, but it's possible that there's a valid purpose for it that I'm missing.

@Eldenroot? Got any idea what this line is for, and whether it's OK to remove it? (We could also remove line 59 while we're at it, since the variable it sets is only used by that line 65).

**Comment by Eldenroot** [comment]
I have no clue :/

So commenting out and deleting the line 59 we should fix this?

**Comment by lairdshaw** [comment]
Deleting lines 59 and 65 should fix it, yes.
