### ISSUE TITLE
Deactivation Error

### ISSUE THREAD

**Issue by schauan** [mybbgroup/FancyBox#78]
when I deactivate the plugin, it will be shown in the plugin list to "install and activate". Also the entry for settings is shown ...
After reinstall I have the settings two times in my forum (1.8.24, php 7.3.x), one time the setting for per-post-gallery is not shown (is in the remained settings entry after deactivate)

**Comment by Eldenroot** [comment]
Did you install for the first time or update from older version?

@lairdshaw

**Comment by lairdshaw** [comment]
There is a problem in the plugin. When settings are deleted, they are deleted by individual name, and I had added a new setting in PR #71, but not added that setting to the list of settings to be deleted on uninstall.

I don't know whether this is what caused the reported problem, but it needs to be fixed in any case.

**Comment by schauan** [comment]
Eldenroot, it was an update of the plugin. I had the 1.0.1 before. But I don't know at the moment whether I had only deactivated it before or deinstalled ...
